import { createFileRoute } from '@tanstack/react-router';
import { useState, type FormEvent } from 'react';
import { ArrowUpRight, Phone, MapPin } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { pageHead } from '@/components/Seo';
import { PageHero, BookingButton, ClosingCTA, WhatsAppIcon, whatsappUrl, directionsUrl } from '@/components/Site';
import balcony from '@/assets/balcony-view.webp';
export const Route = createFileRoute('/contact')({ head: () => pageHead('Contact & Book Your Stay | Dreams Villa A-Frame Cabin', 'Enquire about availability at Dreams Villa A-Frame Cabin near Jibhi. WhatsApp or call +91 85447 30160 for your private Himalayan mountain stay.', '/contact'), component: Contact });
function Contact() {
  const [dates, setDates] = useState({ checkin: '', checkout: '' });
  function enquire(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    const fields = [['Name','name'],['Phone','phone'],['Check-in','checkin'],['Check-out','checkout'],['Guests','guests'],['Message','message']].map(([label,key]) => `${label}: ${String(form.get(key) || '—')}`).join('\n');
    window.open(`https://wa.me/918544730160?text=${encodeURIComponent('Hello Dreams Villa A-Frame Cabin, I would like to enquire about availability and booking.\n\n' + fields)}`, '_blank', 'noopener,noreferrer');
  }
  return <main><PageHero image={balcony} eyebrow="CONTACT / DREAMS VILLA" title="Your Escape Starts Here" subtitle="Tell us when you’d like to come. We’ll be happy to hear from you."/><section className="section container-site contact-grid"><div><p className="eyebrow">LET'S TALK MOUNTAINS</p><h2 className="text-4xl md:text-5xl font-bold leading-tight">Book your mountain escape.</h2><p className="intro-copy">Reach out directly for availability and booking enquiries. No instant booking — just a conversation about your stay.</p><div className="mt-8"><BookingButton>Book your mountain escape</BookingButton></div><div className="mt-10"><a className="contact-option" href="tel:+918544730160"><Phone size={21}/><strong>Call now</strong><ArrowUpRight size={18}/></a><a className="contact-option" href={whatsappUrl} target="_blank" rel="noopener noreferrer"><WhatsAppIcon className="w-5 h-5"/><strong>WhatsApp · +91 85447 30160</strong><ArrowUpRight size={18}/></a><a className="contact-option" href={directionsUrl} target="_blank" rel="noopener noreferrer"><MapPin size={21}/><strong>Get directions</strong><ArrowUpRight size={18}/></a></div></div><div><p className="eyebrow">ENQUIRE FOR YOUR DATES</p><h2 className="text-3xl font-bold mb-7">Send an enquiry</h2><form className="enquiry-form" onSubmit={enquire}><label>Name<input name="name" placeholder="Your name" required/></label><label>Phone<input name="phone" type="tel" placeholder="Your phone number" required/></label><label>Check-in<input name="checkin" type="date" required value={dates.checkin} onChange={e => setDates({...dates,checkin:e.target.value})} min={new Date().toISOString().split('T')[0]}/></label><label>Check-out<input name="checkout" type="date" required value={dates.checkout} onChange={e => setDates({...dates,checkout:e.target.value})} min={dates.checkin || new Date().toISOString().split('T')[0]}/></label><label>Guests<input name="guests" type="number" min="1" placeholder="Number of guests" required/></label><label className="wide">Message<textarea name="message" placeholder="Anything you'd like us to know?"/></label><Button type="submit" size="lg">Send via WhatsApp <ArrowUpRight size={17}/></Button></form><p className="text-xs text-muted-foreground mt-5">Submitting opens WhatsApp with your enquiry details. Your stay is not confirmed until you hear back.</p></div></section><section className="section container-site"><p className="eyebrow">STAY INFORMATION</p><h2 className="text-4xl font-bold">Before you arrive.</h2><div className="info-strip"><div><span>Check-in</span><strong>12:00 PM</strong></div><div><span>Check-out</span><strong>10:00 AM</strong></div><div><span>At arrival</span><strong>Government-approved ID required</strong></div></div></section><ClosingCTA/></main>
}
