import { createFileRoute } from '@tanstack/react-router';
import { Wifi, Mountain, Coffee, Sun, Car, Flower2, Speaker, Heater, Utensils, Shirt, ConciergeBell, House, PanelsTopLeft } from 'lucide-react';
import { pageHead } from '@/components/Seo';
import { PageHero, SplitSection, BookingButton, SectionIntro, ClosingCTA } from '@/components/Site';
import bedroom from '@/assets/ground-floor-bedroom.webp';
import attic from '@/assets/attic-bedroom.webp';
export const Route = createFileRoute('/stay')({ head: () => pageHead('Stay at Dreams Villa | Private A-Frame Cabin Near Jibhi', 'A private A-frame mountain cabin near Jibhi with two double beds across two floors, a balcony, mountain views and home-style dining. Enquire for your dates.', '/stay'), component: Stay });
const amenities = [ [Wifi,'Free Wi-Fi'],[Utensils,'Home-style meals'],[Coffee,'Complimentary breakfast'],[Heater,'Heating on request'],[Speaker,'Bluetooth speaker on request'],[PanelsTopLeft,'Private balcony'],[Mountain,'Mountain views'],[Car,'Parking'],[Flower2,'Garden'],[Sun,'Terrace'],[ConciergeBell,'Room service'],[Shirt,'Laundry service'] ] as const;
function Stay() { return <main><PageHero image={bedroom} eyebrow="YOUR STAY / DREAMS VILLA" title="Your Mountain Hideaway" subtitle="One private cabin. Two inviting floors. All the space you need to feel away from it all."/><section className="section container-site"><SectionIntro eyebrow="A CABIN TO CALL YOUR OWN" title="The simple luxury of being here." text="The primary setup comfortably accommodates around four guests across two double beds — one on each floor of the wooden A-frame duplex."/><div className="info-strip"><div><span>The stay</span><strong>Private A-frame cabin</strong></div><div><span>Sleeping</span><strong>Two double beds</strong></div><div><span>Capacity</span><strong>Around 4 guests</strong></div></div></section><SplitSection image={bedroom} alt="Lower floor double bed and seating at Dreams Villa" eyebrow="LOWER FLOOR" title="Room to unwind."><p>The lower floor is an open living and sleeping area with a double bed, cozy seating and warm wooden surroundings.</p></SplitSection><SplitSection image={attic} alt="Upper attic bedroom with double bed" eyebrow="UPPER FLOOR" title="Rest above it all." reverse><p>An attic-style bedroom with an additional double bed sits above the main floor, connected by the duplex staircase. A private balcony makes the mountain views feel all your own.</p></SplitSection><section className="section container-site"><SectionIntro eyebrow="COMFORTS OF HOME" title="What’s included in your stay."/><div className="amenity-grid">{amenities.map(([Icon,label]) => <div className="amenity-item" key={label}><Icon size={23} strokeWidth={1.5}/><span>{label}</span>{label === 'Laundry service' && <small>Paid service</small>}</div>)}</div><div className="mt-12"><BookingButton>Enquire for your dates</BookingButton></div></section><ClosingCTA/></main> }
