import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight } from 'lucide-react';
import { pageHead } from '@/components/Seo';
import { PageHero, SplitSection, ClosingCTA, AccessNote, exterior } from '@/components/Site';
import downstairs from '@/assets/ground-floor-bedroom.webp';
import upstairs from '@/assets/attic-bedroom.webp';
import balcony from '@/assets/balcony-view.webp';
export const Route = createFileRoute('/the-cabin')({ head: () => pageHead('The A-Frame Cabin | Dreams Villa Near Jibhi', 'Explore the wooden duplex A-frame cabin at Dreams Villa in Bahu near Jibhi: two double beds across two floors, a private balcony and Himalayan views.', '/the-cabin'), component: Cabin });
function Cabin() { return <main><PageHero image={exterior} eyebrow="THE CABIN / DREAMS VILLA" title="The A-Frame" subtitle="A beautiful wooden duplex, built for days that move a little more slowly."/><SplitSection image={downstairs} alt="Ground floor double bed and warm wooden interior" eyebrow="01 / GROUND FLOOR" title="Settle in. Stay awhile."><p>An open-concept living and sleeping area with a comfortable double bed, cozy seating and wooden interiors that make the whole space feel like a mountain home.</p><ul><li>Double bed</li><li>Open living area</li><li>Cozy seating</li><li>Wooden interiors</li></ul></SplitSection><SplitSection image={upstairs} alt="Attic-style upper floor bedroom beneath the A-frame roof" eyebrow="02 / UPPER FLOOR" title="Under the A-frame roof." reverse><p>Climb the duplex staircase to an intimate attic-style bedroom with an additional double bed. The upper floor leads to a private balcony and the views beyond.</p><ul><li>Attic bedroom</li><li>Additional double bed</li><li>Duplex staircase</li><li>Upper-floor balcony</li></ul></SplitSection><SplitSection image={balcony} alt="Private cabin balcony overlooking the Himalayan mountains" eyebrow="03 / THE BALCONY" title="Your front-row seat to the mountains."><p>Take your tea outside, catch the sunrise, or just breathe in the fresh mountain air. The private balcony opens onto panoramic Himalayan views.</p><Link to="/stay" className="text-link">Explore the stay <ArrowRight size={17}/></Link></SplitSection><AccessNote/><ClosingCTA/></main> }
