import { Link, useRouterState } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowUpRight, ArrowRight, Menu, X, Phone, MapPin, Instagram } from 'lucide-react';
import { Button } from '@/components/ui/button';
import exterior from '@/assets/cabins-exterior.webp';
import sunrise from '@/assets/himalayan-sunrise.webp';

export const whatsappUrl = 'https://wa.me/918544730160?text=Hello%20Dreams%20Villa%20A-Frame%20Cabin%2C%20I%20would%20like%20to%20enquire%20about%20availability%20and%20booking.';
export const directionsUrl = 'https://www.google.com/maps/search/?api=1&query=Dreams+villa+A+frame+cabin+Bahu+Himachal+Pradesh';
const navigation = [
  ['Home', '/'], ['The Cabin', '/the-cabin'], ['Stay', '/stay'], ['About', '/about'], ['Dining', '/dining'], ['Experiences', '/experiences'], ['Gallery', '/gallery'], ['Location', '/location'], ['Contact', '/contact'],
] as const;

export function WhatsAppIcon({ className = '' }: { className?: string }) {
  return <svg className={className} viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><path d="M16 .8A15.1 15.1 0 0 0 3 23.6L.9 31l7.6-2a15.2 15.2 0 1 0 7.5-28.2Zm0 27.6a12.4 12.4 0 0 1-6.3-1.7l-.5-.3-4.5 1.2 1.2-4.4-.3-.5a12.4 12.4 0 1 1 10.4 5.7Zm6.8-9.3c-.4-.2-2.2-1.1-2.6-1.2-.3-.1-.6-.2-.8.2-.3.4-1 1.2-1.2 1.4-.2.2-.4.3-.8.1-.4-.2-1.6-.6-3-1.9-1.1-1-1.9-2.2-2.1-2.6-.2-.4 0-.6.2-.8l.6-.7.4-.6c.1-.2 0-.5 0-.7l-1.2-2.8c-.3-.7-.6-.6-.8-.6h-.7c-.2 0-.7.1-1 .5-.4.4-1.4 1.4-1.4 3.3s1.4 3.8 1.6 4c.2.3 2.8 4.3 6.7 5.9.9.4 1.6.6 2.2.7.9.3 1.7.2 2.3.2.7-.1 2.2-.9 2.5-1.8.3-.9.3-1.7.2-1.8-.1-.2-.3-.3-.7-.5Z"/></svg>;
}
export function BookingButton({ children = 'Book Your Stay', variant = 'default', className = '' }: { children?: React.ReactNode; variant?: 'default' | 'outline' | 'light'; className?: string }) {
  return <Button asChild variant={variant === 'light' ? 'light' : variant} size="lg" className={className}><a href={whatsappUrl} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={17}/></a></Button>;
}
export function Header() {
  const [open, setOpen] = useState(false);
  const pathname = useRouterState({ select: s => s.location.pathname });
  return <><header className="site-header"><Link to="/" className="wordmark" onClick={() => setOpen(false)}><span>DREAMS VILLA</span><small>A-FRAME CABIN · BAHU</small></Link><nav className="desktop-nav" aria-label="Main navigation">{navigation.map(([label, path]) => <Link key={path} to={path} className={pathname === path ? 'active' : ''}>{label}</Link>)}</nav><div className="header-actions"><BookingButton className="header-book">Book Your Stay</BookingButton><Button variant="headerIcon" size="icon" className="mobile-toggle" aria-label={open ? 'Close menu' : 'Open menu'} onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</Button></div></header>{open && <nav className="mobile-nav" aria-label="Mobile navigation">{navigation.map(([label, path], i) => <Link key={path} to={path} onClick={() => setOpen(false)}><span className="nav-index">0{i + 1}</span>{label}<ArrowUpRight size={18}/></Link>)}<a href={whatsappUrl} target="_blank" rel="noopener noreferrer" onClick={() => setOpen(false)}>Book Your Stay <ArrowUpRight size={18}/></a></nav>}</>;
}
export function Footer() { return <footer className="footer"><div className="footer-top"><div><p className="eyebrow">A QUIETER KIND OF GETAWAY</p><h2>Come a little closer<br/>to the mountains.</h2><BookingButton variant="light">Book your mountain escape</BookingButton></div><div className="footer-links"><div><span>EXPLORE</span>{navigation.slice(1, 7).map(([label,path]) => <Link key={path} to={path}>{label}</Link>)}</div><div><span>FIND US</span><p>Bahu (Lushal), Himachal Pradesh 175123<br/>Near Jibhi</p><a href="tel:+918544730160">+91 85447 30160</a><a href={directionsUrl} target="_blank" rel="noopener noreferrer">Get directions ↗</a></div></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Dreams Villa A-Frame Cabin</span><span>Made for slower days in Bahu, Himachal Pradesh</span></div></footer> }
export function FloatingWhatsApp() { return <a className="floating-whatsapp" href={whatsappUrl} target="_blank" rel="noopener noreferrer" aria-label="Enquire on WhatsApp" title="Enquire on WhatsApp"><WhatsAppIcon className="w-6 h-6"/></a> }
export function PageHero({ image, eyebrow, title, subtitle, position = 'center' }: { image: string; eyebrow: string; title: string; subtitle?: string; position?: string }) { return <section className="page-hero"><img src={image} alt={eyebrow + ' at Dreams Villa A-Frame Cabin'} className="hero-photo" style={{objectPosition: position}} fetchPriority="high"/><div className="hero-shade"/><div className="page-hero-content container-site"><p className="eyebrow light">{eyebrow}</p><h1>{title}</h1>{subtitle && <p className="hero-subtitle">{subtitle}</p>}</div><span className="hero-side-note">DREAMS VILLA / HIMACHAL PRADESH</span></section> }
export function SectionIntro({ eyebrow, title, text, centered = false }: { eyebrow: string; title: string; text?: string; centered?: boolean }) { return <div className={'section-intro ' + (centered ? 'centered' : '')}><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{text && <p className="intro-copy">{text}</p>}</div> }
export function SplitSection({ image, alt, eyebrow, title, children, reverse = false }: { image: string; alt: string; eyebrow: string; title: string; children: React.ReactNode; reverse?: boolean }) { return <section className={'split-section container-site ' + (reverse ? 'reverse' : '')}><div className="split-photo-wrap"><img src={image} alt={alt} loading="lazy"/></div><div className="split-copy"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><div className="body-copy">{children}</div></div></section> }
export function AccessNote() { return <section className="access-section"><div className="container-site access-grid"><div><p className="eyebrow">THE JOURNEY IS PART OF THE STAY</p><h2>A Little Walk to Your Mountain Cabin</h2><p>Parking is approximately 100–200 meters from the cabin. The final approach is a short uphill, off-road walk that can be rocky. Bhola can assist with luggage.</p></div><div className="access-card"><span className="access-symbol">↗</span><p className="eyebrow">GOOD TO KNOW BEFORE YOU ARRIVE</p><p>Because the path is rocky and uphill, the stay may not be suitable for elderly guests or travellers with serious mobility issues.</p><Link to="/location" className="text-link">Plan your arrival <ArrowRight size={17}/></Link></div></div></section> }
export function ClosingCTA() { return <section className="closing-cta"><img src={sunrise} alt="Sunrise over the Himalayan mountains near Dreams Villa" loading="lazy"/><div className="closing-shade"/><div className="container-site closing-content"><p className="eyebrow light">YOUR MOUNTAIN MOMENT AWAITS</p><h2>Leave the ordinary<br/>down in the valley.</h2><BookingButton variant="light">Book your mountain escape</BookingButton></div></section> }
export { exterior, sunrise };
